baseURL = "https://maixuu.com/"
languageCode = "en-us"
title = "Mai's Blog"
theme = "archie"
copyright = "© Mai"
summaryLength = 10

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "If I ever make it home, I'll tell the tale."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
    favicon = "/assets/favicon.ico"

# Social Tags

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:maizehsu02@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/maixu/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "github.com/maizehsu"

[[params.social]]
name = "Douban"
icon = "film"
url = "douban.com/people/maixu02/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true